package handwriting.learners.som;

import handwriting.core.Drawing;
import org.junit.Test;

/**
 * Created by My_Nguyen on 10/12/15.
 */
public class SOMNodeTest {
    @Test
    public void ConstructorShouldWorkAsExpected(){
        int testX =0;
        int testY =0;
        int drawingX = 10;
        int drawingY = 5;
        SOMNode node = new SOMNode(testX, testY, drawingX, drawingY);
        SOMPoint[][] points = node.getPoints();
        for(int i =0; i < drawingX; i++){
            for (int j =0; j < drawingY; j++){
                System.out.println(points[i][j]);
            }
        }

    }
    @Test
    public void ShouldBeEqualWhenTested (){
        String encodedDrawing = "40|40|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOXXXXXXXXXOOOOOOOOOOOOOOOO|OOOOOOOOOOOOXXXXXXXXXXXXXXOOOOOOOOOOOOOO|OOOOOOOOOXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOO|OOOOOOOXXXXXXXXXXOOOOOXXXXXXXOOOOOOOOOOO|OOOOOOOXXXXXXXXOOOOOOOOOXXXXXOOOOOOOOOOO|OOOOOOXXXXXXOOOOOOOOOOOOOOXXXXOOOOOOOOOO|OOOOOXXXXXOOOOOOOOOOOOOOOOXXXXOOOOOOOOOO|OOOOOXXXXOOOOOOOOOOOOOOOOOOXXXXOOOOOOOOO|OOOOOXXXOOOOOOOOOOOOOOOOOOOXXXXXOOOOOOOO|OOOOOXXXOOOOOOOOOOOOOOOOOOOOXXXXOOOOOOOO|OOOOOXXXOOOOOOOOOOOOOOOOOOOOXXXXOOOOOOOO|OOOOOXXXOOOOOOOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOXXXOOOOOOOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOXXXXXOOOOOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOXXXXXOOOOOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOXXXXXXXOOOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOOOXXXXXXOOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOOOOXXXXXXOOOOOOOOOOOOOOOXXXOOOOOOOO|OOOOOOOOOXXXXXOOOOOOOOOOOOOOXXXXOOOOOOOO|OOOOOOOOOOXXXXXOOOOOOOOOOOOOXXXXOOOOOOOO|OOOOOOOOOOOXXXXXOOOOOOOOOOXXXXXXOOOOOOOO|OOOOOOOOOOOOXXXXXXOOOOOOXXXXXXXOOOOOOOOO|OOOOOOOOOOOOOXXXXXXXXXXXXXXXXXOOOOOOOOOO|OOOOOOOOOOOOOOXXXXXXXXXXXXXXOOOOOOOOOOOO|OOOOOOOOOOOOOOOOXXXXXXXXXXOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|";
        Drawing d = new Drawing(encodedDrawing);
        SOMNode testNode = new SOMNode(0,0, d.getWidth(), d.getHeight());
        System.out.println(testNode.calculateDistToDrawing(d));
    }

}
